# Generated by Django 4.2.11 on 2024-05-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_trade_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
