# Generated by Django 4.2.11 on 2024-05-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_trade_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='amount',
        ),
    ]
