# Generated by Django 4.2.11 on 2024-05-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.PositiveIntegerField(),
        ),
    ]
